# docker-compose.yaml
version: '3.8'
services:
  app:
    build: .
    container_name: ${COOLIFY_CONTAINER_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    ports:
      - "3000:3000"
    networks:
      - coolify

networks:
  coolify:
    external: true
