version: '3.8'
services:
  app:
    build: .
    container_name: ${COOLIFY_CONTAINER_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - coolify
    labels:
      traefik.enable: true
      traefik.http.routers.${COOLIFY_SERVICE_ID}.rule: Host(`${COOLIFY_DOMAIN}`)
      traefik.http.services.${COOLIFY_SERVICE_ID}.loadbalancer.server.port: 3000
      coolify.managed: "true"

networks:
  coolify:
    external: true
